```{r}
library(tidyverse)
library(ggplot2)
```


```{r}
df = read.csv('bar_pass_prediction.csv')
```

```{r}
str(df)
summary(df)
```

```{r}
idsUnique <- n_distinct(df$ID)
idsTotal <- nrow(df)
idd <- idsTotal - idsUnique

print(paste('Number of duplicate IDs:', idd))

```


```{r}
na_counts_base <- lapply(df, function(x) sum(is.na(x)))

print(na_counts_base)

ggplot(df, aes(x = "", fill = factor(pass_bar))) +
  geom_bar(width = 1) +
  coord_polar("y", start = 0) +
  theme_void() +
  ggtitle("Pass Bar") +
  scale_fill_discrete(name = "Pass Bar") +
  geom_text(aes(label = paste0(round(..count../sum(..count..)*100), "%")),
            stat = "count",
            position = position_stack(vjust = 0.5))

```



```{r}
table(df$gender)
```

```{r}
sum(is.na(df$gender))

df <- df %>%
  mutate(
    gender = case_when(
      gender == "male" ~ 1,
      gender == "female" ~ 0,
    )
  )
```


```{r}
df <- df %>% 
  filter(!is.na(gender))
```



```{r}
df$lsat <- as.integer(df$lsat)
summary(df$lsat)
```

```{r}
numeric_df <- df %>% 
  select(where(is.numeric))

cor_matrix <- cor(numeric_df)
cor_matrix
```


```{r}
cor_matrix_long <- cor_matrix %>%
  as.data.frame() %>%
  rownames_to_column(var = "var1") %>%
  pivot_longer(cols = -var1, names_to = "var2", values_to = "correlation")

ggplot(cor_matrix_long, aes(x = var1, y = var2, fill = correlation)) +
  geom_tile() +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0) +
  labs(title = "Корреляционная матрица") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r}
pass_bar_corr <- cor(numeric_df, use = "complete.obs")["pass_bar", ]

pass_bar_corr[order(-abs(pass_bar_corr))]
```





```{r}
gender_corr <- cor(numeric_df, use = "complete.obs")["gender", ]

gender_corr[order(-abs(gender_corr))]

```

```{r}
df <- df %>% 
  select(-sex, -male)
```


```{r}
df_race <- df %>% select(race, race1, race2, other, asian, black, hisp)
head(df_race)
```


```{r}
colSums(is.na(df_race))

sum(is.na(df_race$race) & is.na(df_race$race1) & is.na(df_race$race2))

unique(df_race$race)
unique(df_race$race1)
unique(df_race$race2)
```


```{r}
# Анализ black студентов
cat("black students in race1:", sum(df_race$race1 == "black", na.rm = TRUE), "\n")
cat("black students in column black:", sum(df_race$black, na.rm = TRUE), "\n")
cat("Number of black students in one column and not the other:", 
    sum(df_race$black == 1 & df_race$race1 != "black", na.rm = TRUE), "\n")
```

```{r}
# Анализ hisp студентов
cat("hisp students in race1:", sum(df_race$race1 == "hisp", na.rm = TRUE), "\n")
cat("hisp students in column hisp:", sum(df_race$hisp, na.rm = TRUE), "\n")
cat("Number of hisp students in one column and not the other:",
    sum(df_race$hisp == 1 & df_race$race1 != "hisp", na.rm = TRUE), "\n")
```
Будем опираться на колонку race1

```{r}
# Анализ asian студентов
cat("asian students in race1:", sum(df_race$race1 == "asian", na.rm = TRUE), "\n")
cat("asian students in column asian:", sum(df_race$asian, na.rm = TRUE), "\n")
cat("Number of asian students in one column and not the other:",
    sum(df_race$asian == 1 & df_race$race1 != "asian", na.rm = TRUE), "\n")
```

```{r}
table(df$race1)
```



```{r}
race_counts <- df %>%
  mutate(race1 = ifelse(is.na(race1), "unknown", race1)) %>%
  count(race1) %>%
  mutate(
    race = case_when(
      race1 == "white" ~ "white",
      race1 == "black" ~ "black",
      race1 == "hisp" ~ "hisp",
      race1 == "asian" ~ "asian",
      race1 == "other" ~ "other",
      TRUE ~ "unknown"
    ),
    `bar takers` = 100 * n / nrow(df),
    population = case_when(
      race == "white" ~ 59.3,
      race == "black" ~ 12.6,
      race == "hisp" ~ 18.9,
      race == "asian" ~ 5.9,
      race == "other" ~ 3.3,
      TRUE ~ NA
    )
  )

race_categories <- c("white", "black", "hisp", "asian", "other", "unknown")

per_pass <- map_dbl(race_categories, ~ {
  if (.x == "unknown") {
    100 * sum(is.na(df$race1) & df$pass_bar == 1, na.rm = TRUE) / 
      sum(is.na(df$race1), na.rm = TRUE)
  } else {
    100 * sum(df$race1 == .x & df$pass_bar == 1, na.rm = TRUE) / 
      sum(df$race1 == .x, na.rm = TRUE)
  }
})

race_counts <- race_counts %>%
  mutate(`percent passed` = per_pass[match(race, race_categories)])

print(race_counts)
```



```{r}
sum(is.na(df$race1))
df <- df %>% mutate(race1 = ifelse(is.na(race1), "white", race1))

# One-hot encoding
library(caret)
dummy <- dummyVars(~ race1, data = df)
df_ohe <- predict(dummy, newdata = df) %>% as.data.frame()

df <- df %>% 
  select(-race1, -black, -hisp, -asian, -race2, -race) %>% 
  bind_cols(df_ohe)
```

```{r}
df <- df %>% select(-race1)
```



```{r}
corrmat <- df %>% 
  select(where(is.numeric)) %>%
  cor(use = "complete.obs") %>%
  abs()

upper <- corrmat
upper[lower.tri(upper, diag = TRUE)] <- NA

to_drop <- colnames(upper)[apply(upper, 2, function(x) any(x > 0.95, na.rm = TRUE))]

print(to_drop)
```

Дропнем parttime и gpa, а также bar_passed (который совпадает с pass_bar)
```{r}
df <- df %>% select(-parttime, -gpa, -bar_passed)
```

```{r}
library(corrplot)
df_dec <- df %>% select(decile1b, decile1, zfygpa, decile3, zgpa)
head(df_dec)
```

```{r}
corrmat <- cor(df_dec, use = "complete.obs")
corrplot(corrmat, 
         method = "color",
         type = "upper",
         tl.col = "black",
         tl.srt = 45,
         addCoef.col = "black",
         number.cex = 0.7,
         mar = c(0,0,1,0),
         title = "Correlation Matrix")

```

```{r}
corrmat_df <- as.data.frame(corrmat)
corrmat_df %>% arrange(desc(decile1)) %>% select(decile1)
corrmat_df %>% arrange(desc(decile3)) %>% select(decile3)
```

```{r}
colSums(is.na(df_dec))
```

```{r}
df %>% filter(is.na(decile1) & !is.na(decile1b)) %>% nrow()
```

```{r}
df <- df %>% select(-decile1b)
```


```{r}
df %>% filter(is.na(decile1) & !is.na(zfygpa)) %>% nrow()
df %>% filter(!is.na(decile1) & is.na(zfygpa)) %>% nrow()
```


```{r}
df_zfy <- df %>% select(zfygpa, decile1)
head(df_zfy)
```

```{r}
df_zfy %>% filter(is.na(decile1) & !is.na(zfygpa)) %>% head()
```

```{r}
condlist <- list()
for(i in 1:10) {
  condlist[[i]] <- min(df_zfy$zfygpa[df_zfy$decile1 == i], na.rm = TRUE)
}
```


```{r}
condlist
```

```{r}
condlist <- lapply(1:10, function(i) {
  min(df_zfy$zfygpa[df_zfy$decile1 == i], na.rm = TRUE)
}) %>% unlist()


thresholds <- data.frame(
  decile = 9:1,
  threshold = (condlist[9:1] + condlist[10:2])/2
)


assign_decile <- function(zfygpa_val) {
  if(is.na(zfygpa_val)) return(NA)
  for(i in 1:nrow(thresholds)) {
    if(zfygpa_val > thresholds$threshold[i]) {
      return(thresholds$decile[i])
    }
  }
  return(1)
}

df <- df %>%
  mutate(decile1 = ifelse(is.na(decile1),
                         sapply(zfygpa, assign_decile),
                         decile1))
```




```{r}
df_z <- df %>% select(zgpa, decile3)
head(df_z)
```

```{r}
df_z %>% filter(is.na(decile3) & !is.na(zgpa)) %>% head()
```

```{r}
condlist <- list()
for(i in 1:10) {
  condlist[[i]] <- min(df_z$zgpa[df_z$decile3 == i], na.rm = TRUE)
}
```

```{r}
condlist
```



```{r}
condlist <- lapply(1:10, function(i) {
  min(df_z$zgpa[df_z$decile3 == i], na.rm = TRUE)
}) %>% unlist()

condlist <- lapply(1:10, function(i) {
  min(df_z$zfygpa[df_z$decile3 == i], na.rm = TRUE)
}) %>% unlist()


thresholds <- data.frame(
  decile = 9:1,
  threshold = (condlist[9:1] + condlist[10:2])/2
)

assign_decile <- function(zgpa_val) {
  if(is.na(zgpa_val)) return(NA)
  for(i in 1:nrow(thresholds)) {
    if(zgpa_val > thresholds$threshold[i]) {
      return(thresholds$decile[i])
    }
  }
  return(1)
}


df <- df %>%
  mutate(decile3 = ifelse(is.na(decile3),
                         sapply(zgpa, assign_decile),
                         decile3))

```

```{r}
df_dec <- df %>% select(decile1, zfygpa, decile3, zgpa)
colSums(is.na(df_dec))
```


```{r}
df <- df %>% select(-zfygpa, -zgpa)
```



```{r}
pass_bar_corr <- cor(numeric_df, use = "complete.obs")["pass_bar", ]

pass_bar_corr[order(-abs(pass_bar_corr))]
```

